# Generated by Django 4.1.5 on 2023-01-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
