# Generated by Django 4.1.5 on 2023-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_pledge_amount_alter_project_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
